### ISSUE TITLE
Adaptando a sufel para UBL2.1

### ISSUE THREAD

**Issue by eilsongithub** [giansalex/sufel#15]
Estoy tratando de adaptar sufel para UBL2.1.
Pero cuando trato de traer los tags obtengo esto:

->setEmisor($this->getFirst('cac:AccountingSupplierParty/cac:Party/cac:PartyIdentification/**cbc:ID**))
Obtengo un error 500

->setEmisor($this->getFirst('cac:AccountingSupplierParty/cac:Party/cac:PartyIdentification/**cbc:ID schemeID="6"**))
Obtengo vacio

Sin embargo para los campos de razón social  los trae correctamente ... ¿Cual será el error?

**Comment by eilsongithub** [comment]
Pero no me extrae el RUC....¿?...

**Comment by eilsongithub** [comment]
Disculpas si me extrae el RUC, pero me presenta error 500...

**Comment by eilsongithub** [comment]
Estoy extrayendo tipo documento del cliente del xml.
![image](https://user-images.githubusercontent.com/44086967/50402956-b7040d00-0768-11e9-80cb-09c76abe0a95.png)

de esta manera 
![image](https://user-images.githubusercontent.com/44086967/50403458-9c339780-076c-11e9-8ae3-d552e5d35152.png)

Pero obtengo éste error:

![image](https://user-images.githubusercontent.com/44086967/50402973-dac75300-0768-11e9-805e-3f4a80cd8128.png)

**Comment by eilsongithub** [comment]
Si le puede servir a alguien. 
he modificado esto
![image](https://user-images.githubusercontent.com/44086967/50403940-cbe49e80-0770-11e9-94e8-ca9c3c848b06.png)

en XmlExtractor.php y funcionó.

**Comment by giansalex** [comment]
Hola eilson, qué bueno que hayas encontrado la solución, sería de mayor ayuda si pudieras hacer un fork y realizar el cambio, obtener la versión del UBL en el tag <UBLVersion> y según ello usar el código que agregaste

**Comment by eilsongithub** [comment]
Estimado Giansalex, lo intentaré.

**Comment by giansalex** [comment]
Esta hecho en 7471d083e7c5a72dc2a01286486661212bdf3d52
