### ISSUE TITLE
Descarga de XML devuelve caracteres errados

### ISSUE THREAD

**Issue by yersey20037** [giansalex/sufel#19]
Giansalex, estoy accediendo a sufel mediante CURL y consigo respuesta pero esta no se muestra en formato xml y no sale directo para descarga.
Mi código 
`<?php
	$authorization = "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6WyJkb2N1bWVudCJdLCJkb2MiOiIyIiwiZXhwIjoxNTcyMDQ4MDc5fQ.zDEeTEDYK8dXC8nUCVfzVUENlIEMVh90Ab7CtendSRo"; 
	$cliente = curl_init();
	curl_setopt($cliente, CURLOPT_URL, "http://mipagina.com/sufel/public/api/document/resource/xml");
	curl_setopt($cliente, CURLOPT_HTTPHEADER, array('text/xml; charset=utf-8',$authorization));
	curl_setopt($cliente, CURLOPT_RETURNTRANSFER, 1);
	$respuesta = curl_exec($cliente);
	curl_close($cliente);
	$respuesta = explode("\n\r\n", $respuesta);
	$headers = $respuesta[0];
	echo $headers;
?>
`
Este me devuelve esto:
![708A5EF6-2057-4EEC-A473-3E01E4667CD7](https://user-images.githubusercontent.com/56704596/67609959-2e257b80-f755-11e9-9b01-e46aceeabc34.jpeg)
Que le falta a mi código para que dé frente me descargue el xml en formato correcto?

**Comment by giansalex** [comment]
Hola, podrías escribir toda la respuesta en un archivo, ej: `file_put_contents('file.xml', $respuesta);`, y ver que es lo que esta trayendo

**Comment by yersey20037** [comment]
este codigo:
`<?php
	$authorization = "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6WyJkb2N1bWVudCJdLCJkb2MiOiIyIiwiZXhwIjoxNTcyMDQ4MDc5fQ.zDEeTEDYK8dXC8nUCVfzVUENlIEMVh90Ab7CtendSRo"; 
	$cliente = curl_init();
	curl_setopt($cliente, CURLOPT_URL, "http://createcperu.com/sufel/public/api/document/resource/xml");
	curl_setopt($cliente, CURLOPT_HTTPHEADER, array('text/xml; charset=utf-8',$authorization));
	curl_setopt($cliente, CURLOPT_RETURNTRANSFER, 1);
	$respuesta = curl_exec($cliente);
	file_put_contents('file.xml',$respuesta);
	curl_close($cliente);
?>
`
me devuelve un archivo xml vacio

**Comment by yersey20037** [comment]
con file_put_contents('file.xml', $respuesta) genera correctamente el xml.
pero se guarda en el servidor como hago para que me aparesca la ventana de descarga directamente al ejecutar?

**Comment by giansalex** [comment]
Puede ser algo asi:
```php
header('Content-Type: text/xml'); 
header('Content-Disposition: attachment; filename="file.xml"');
echo $respuesta;
```

**Comment by yersey20037** [comment]
doc tuve problemas para hacer la llamada al archivo php enviando desde javascrip
asi que comence a hacer todo el proceso desde php con curl comenzando por la autenticacion del documento
pero no puedo obtener el token separado de toda la cadena ya que por lo que entendi CURL me devuelve una cadena y no un array del que pueda sacar solo el campo token.
este es mi codigo con el que llamo
`function loguear(){
$emisor="20544097963";
$tipo="01";
$documento="F001-00000001";
$fecha="2019-08-09";
$total="20.00";
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,"http://mipagina/sufel/public/api/document/auth");
curl_setopt($ch, CURLOPT_POST, TRUE);
curl_setopt($ch, CURLOPT_POSTFIELDS, "emisor=$emisor&tipo=$tipo&documento=$documento&fecha=$fecha&total=$total");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
$respuesta = curl_exec ($ch);
curl_close ($ch);
print_r($respuesta);
}`
esto me devuelve la cadena completa pero al intenertar obtener solo el campo token con
print_r($respuesta["token"]);
al cargar la pagina me muestra en consola 
SyntaxError: '' string literal contains an unescaped line break
y no se ejecuta. leyendo sobre esto es porque CURL esta devolviendo una cadena en lugar de un array.

**Comment by giansalex** [comment]
es lo normal, devuelve la respuesta tal cual responde el servidor, en este caso es un json(cadena), tendrias que hacer algo como:
```php
$auth = json_decode($respuesta, true);
print_r($auth['token']);
```

**Comment by yersey20037** [comment]
Ok gracias

**Comment by yersey20037** [comment]
Ok gracias
