### ISSUE TITLE
especificar que carpeta contiene los archivos a subir

### ISSUE THREAD

**Issue by yersey20037** [giansalex/sufel#20]
Giansalex, disculpa tengo la duda de como especificar la carpeta local donde se encuentran el XML y el PDF.
actualmente subo los archivos manualmente a la carpeta public y desde ahi los llamo para que se integren a la API-SUFEL con este codigo:
`

<button onclick="myFunction()">subir archivos</button><br>
<div id="cont1"></div>
<?php
$xml = base64_encode(file_get_contents("20547202020-01-F001-00000001.XML"));
$pdf= base64_encode(file_get_contents("20547202020-01-F001-00000001.PDF"));
$content = ['xml' => $xml, 'pdf' => $pdf];
?>
<script>
function myFunction() {
var data = {
xml: "<?php echo $xml?>",
pdf: "<?php echo $pdf?>",
}
$.ajax({
url: 'http://mipagina.com/sufel/public/api/company/documents',
type: 'POST',
dataType: 'json',
contentType: "application/json; charset=utf-8",
data: JSON.stringify(data),
headers: { 
        Authorization: "Bearer 2eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzY29wZSI6WyJjb21wYW55Il0sInJ1YyI6IjIwNTQ3NzAxMjA5IiwiZXhwIjoxNTcyNzA2NDc5fQ.AL_f4vXWtbtW77WN9dF1eaaz5EAyplaPUX6aJ1JOALk"
},
		success:function(r,extStatus, xhr){
			console.log(extStatus);
			document.getElementById('cont1').innerHTML=xhr.status;
		},
		error: function (jqXHR, exception) {
		    document.getElementById('cont1').innerHTML=jqXHR.status;
			console.log(jqXHR);
			// Your error handling logic here..
		}
});
}
</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
`
pero lo correcto seria especificar la carpeta local de donde leer los archivos, por ejemplo 
c:\archivos_pdf y c:\archivos_xml pero no encuentro la manera correcta de poder especificar las carpetas donde PHP debe buscar los archivos.
Seria una gran ayuda que me pudieras ayudar con esto.

Saludos y muchas gracias

**Comment by yersey20037** [comment]
![Captura](https://user-images.githubusercontent.com/56704596/68065843-ed050c80-fcfc-11e9-99d4-105d11ead1b3.JPG)
no se si mi codigo se ve bien aqui una captura

**Comment by giansalex** [comment]
Hola, si los archivos ya la tienes del lado del servidor, no es necesario que lo hagas desde Javascript, puedes hacerlo directo desde PHP. La ruta donde se guardarán los archivos después de subirlo se indica aqui
https://github.com/giansalex/sufel-rest/blob/master/src/settings.php#L27

**Comment by yersey20037** [comment]
Tengo un sistema propio que genera el xml y pdf y los guarda en una carpeta local de mi cliente desde el cual con un localhost quiero que busque en esa carpeta y envié al servidor por medio de la api sufel

**Comment by yersey20037** [comment]
Es posible que con una pc con localhost leer esa carpeta en el pc buscar el xml y pdf y enviarlos a sufel que está en un hosting?

**Comment by giansalex** [comment]
Los archivos pueden enviarse desde cualquier origen, usando esa ruta del API
