### ISSUE TITLE
diferenciar el mensaje de respuesta cuando el documento ya existe en la BD

### ISSUE THREAD

**Issue by yersey20037** [giansalex/sufel#21]
Buenas Giansalex, una consulta a que parametro debo llamar para saber cuando el documento ya fue enviado anteriormente, por que durante mis pruebas si el documento existe o no, me devuelve en los dos casos codigo 200 pero como puedo diferenciar cuando se guardo uno nuevo o el documento ya existe.
Saludos 
Gracias

**Comment by giansalex** [comment]
Antes salia un error, pero ya generaba problemas, asi que siguiendo el principio de idempotencia siempre devuelve HTTP 200, podria buscarse una variante para cuando ya exista
