### ISSUE TITLE
Enviar correo al guardar el documento

### ISSUE THREAD

**Issue by yersey20037** [giansalex/sufel#23]
Giansalex, por donde podría comenzar si quiero que cuando se suba un documento también se envíe el xml y pdf al correo del cliente.
Saludos
Gracias por la ayuda y paciencia 
Actualmente tengo corriendo en un hosting SUFEL consumido por sufel-angular y le envío los archivos con un ejecutable que hice en Java y todo funciona correctamente solo tengo pendiente lo de enviar los archivos al correo del cliente una vez que se guardo en SUFEL.

**Comment by giansalex** [comment]
Hola @yersey20037,  tendría que enviarse el correo en los parametros o extraerlo del XML si esta incluido; en este [metodo](https://github.com/giansalex/sufel/blob/master/src/app/Controllers/CompanyApi.php#L97) se debe agregar el envio, empleando librerias como [PHPMailer](https://github.com/PHPMailer/PHPMailer)

**Comment by yersey20037** [comment]
me parece que lo correcto seria agregar el campo correo en SUFEL-ANGULAR cuando el cliente crea su usuario y contraseña y eso enviarlo a la api SUFEL que cuando reciba una factura nueva de ese cliente revise si el cliente tiene registrado un correo y haga el envio.
esta bien lo planteado o generaria mucho cambio? en la api SUFEL  como en SUFEL-ANGULAR.

**Comment by giansalex** [comment]
Si esta registrado, claro se podría.
